version: 2

references:

  workspace_root: &workspace_root
      ~/code

  container_config: &container_config
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: *workspace_root

    environment:
      JVM_OPTS: "-Xmx3200m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
    key: weatherforecast-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    resource_class: medium+
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Add Google Services configuration
          command: echo $GOOGLE_SERVICES_CONFIGURATION | base64 --decode > ~/code/app/google-services.json

      - run:
          name: Initial build
          command: ./gradlew --no-daemon --stacktrace assembleRelease

      - store_artifacts:
          path: ~/code/app/build/outputs/apk/
          destination: apks/

      - store_artifacts:
          path: ~/code/app/build/outputs/mapping/
          destination: mapping/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"
            - "~/.m2"
            - "/opt/android-sdk-linux/licenses/"

  check:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Checks
          command: ./gradlew --no-daemon --stacktrace lintRelease checkRelease detektCheck

      - store_artifacts:
          path: ~/code/app/build/reports/
          destination: lint_reports/

      - store_artifacts:
          path: ~/code/base/build/reports/detekt/
          destination: deteckt/

  test:
    <<: *container_config
    parallelism: 3
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Tests
          command: |
            upload-coverage:
    environment: 
      - CC_TEST_REPORTER_ID: e108ce35be2fcd98a66d6265e551c5354e1737b2bc58cfd22cfa61beda1b9a8c
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 3 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.j

      - store_artifacts:
          path: app/build/reports/tests/
          destination: tests_reports/

      - store_artifacts:
          path: app/build/reports/jacoco/
          destination: jacoco_reports/

      - store_test_results:
          path: ~/code/app/build/test-results

workflows:

  version: 2

  build_check_tests_deploy:
    jobs:
      - build
      - check:
          requires:
            - build
      - test:
          requires:
            - build
